package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/owainlewis/neo/internal/llm"
	"github.com/owainlewis/neo/internal/tools"
)

const generatedHeader = "<!-- Generated by `go run ./cmd/neo-docs`. Do not edit by hand. -->\n\n"

type page struct {
	Path    string
	Content string
}

func main() {
	check := flag.Bool("check", false, "fail if generated developer docs are out of date")
	flag.Parse()

	pages, err := buildPages()
	if err != nil {
		fatal(err)
	}
	if *check {
		if err := checkPages(pages); err != nil {
			fatal(err)
		}
		return
	}
	if err := writePages(pages); err != nil {
		fatal(err)
	}
	for _, page := range pages {
		fmt.Printf("generated %s\n", page.Path)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

func buildPages() ([]page, error) {
	configYAML, err := os.ReadFile(filepath.Join("internal", "config", "defaults", "neo.yaml"))
	if err != nil {
		return nil, fmt.Errorf("read default config: %w", err)
	}
	specs := toolSpecs()
	return []page{
		{Path: filepath.Join("docs", "developer", "index.md"), Content: indexPage()},
		{Path: filepath.Join("docs", "developer", "architecture.md"), Content: architecturePage()},
		{Path: filepath.Join("docs", "developer", "cli.md"), Content: cliPage()},
		{Path: filepath.Join("docs", "developer", "config.md"), Content: configPage(string(configYAML))},
		{Path: filepath.Join("docs", "developer", "sessions.md"), Content: sessionsPage()},
		{Path: filepath.Join("docs", "developer", "tools.md"), Content: toolsPage(specs)},
		{Path: filepath.Join("docs", "developer", "prompt-caching.md"), Content: promptCachingPage()},
	}, nil
}

func toolSpecs() []llm.ToolSpec {
	reg := tools.NewRegistry(
		tools.Bash{Timeout: 2 * time.Minute},
		tools.ReadFile{},
		tools.WriteFile{},
		tools.EditFile{},
		tools.Grep{Root: "."},
		tools.Glob{Root: "."},
	)
	specs := reg.Specs()
	sort.Slice(specs, func(i, j int) bool { return specs[i].Name < specs[j].Name })
	return specs
}

func writePages(pages []page) error {
	for _, page := range pages {
		if err := os.MkdirAll(filepath.Dir(page.Path), 0o755); err != nil {
			return fmt.Errorf("create %s: %w", filepath.Dir(page.Path), err)
		}
		if err := os.WriteFile(page.Path, []byte(page.Content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", page.Path, err)
		}
	}
	return nil
}

func checkPages(pages []page) error {
	var stale []string
	for _, page := range pages {
		got, err := os.ReadFile(page.Path)
		if err != nil {
			stale = append(stale, page.Path)
			continue
		}
		if !bytes.Equal(got, []byte(page.Content)) {
			stale = append(stale, page.Path)
		}
	}
	if len(stale) > 0 {
		return fmt.Errorf("developer docs are out of date; run `go run ./cmd/neo-docs`: %s", strings.Join(stale, ", "))
	}
	return nil
}

func indexPage() string {
	return generatedHeader + `# Neo Developer Docs

These docs are generated from the repository and are intended for both humans and Neo itself.

Start here when changing Neo:

- [Architecture](architecture.md) explains the module boundaries.
- [CLI](cli.md) documents commands and startup flow.
- [Configuration](config.md) documents config loading and feature flags.
- [Sessions](sessions.md) documents persisted conversations and gateway mapping.
- [Tools](tools.md) documents the built-in tool surface.
- [Prompt caching](prompt-caching.md) documents structured system prompt blocks.

Regenerate:

` + "```bash" + `
go run ./cmd/neo-docs
` + "```" + `

Check:

` + "```bash" + `
go run ./cmd/neo-docs --check
` + "```" + `
`
}

func architecturePage() string {
	return generatedHeader + `# Architecture

Neo is a small Go coding agent. The core agent loop is policy-free: it owns message state, calls an LLM provider, emits events, and runs injected tools. Product behavior is layered around that loop.

## Main Modules

| Path | Responsibility |
| --- | --- |
| ` + "`cmd/neo/`" + ` | CLI entry point, command dispatch, chat session startup. |
| ` + "`cmd/neo-docs/`" + ` | Deterministic developer documentation generator. |
| ` + "`internal/agent/`" + ` | Core agent loop, transcript state, event model, tool-use continuation. |
| ` + "`internal/auth/`" + ` | OpenAI ChatGPT/Codex OAuth login, token refresh, and stored subscription credentials. |
| ` + "`internal/compact/`" + ` | Compaction interface, no-op default, and safe split helpers for future strategies. |
| ` + "`internal/config/`" + ` | Config discovery, defaults, and feature flags. |
| ` + "`internal/llm/`" + ` | Provider-neutral request/response types and system prompt blocks. |
| ` + "`internal/llm/anthropic/`" + ` | Anthropic provider adapter. |
| ` + "`internal/llm/openai/`" + ` | OpenAI provider adapters for API-key Responses API calls and ChatGPT/Codex subscription calls. |
| ` + "`internal/permission/`" + ` | Tool-call permission policy and workspace path boundary checks. |
| ` + "`internal/projectctx/`" + ` | AGENTS.md discovery and prompt augmentation. |
| ` + "`internal/session/`" + ` | File-backed session metadata and transcripts. |
| ` + "`internal/skills/`" + ` | Skill discovery, catalog rendering, and $name expansion. |
| ` + "`internal/tools/`" + ` | Built-in tools exposed to the model. |
| ` + "`internal/tui/`" + ` | Bubble Tea terminal UI and transcript rendering. |
| ` + "`internal/workspace/`" + ` | Workspace helpers shared by project-context features. |

## Chat Startup Flow

1. ` + "`cmd/neo`" + ` loads config.
2. ` + "`mustProvider`" + ` selects Anthropic or OpenAI. OpenAI defaults to API-key auth; ` + "`openai_auth: subscription`" + ` builds the Codex subscription provider from stored OAuth credentials.
3. The CLI creates or loads a session from ` + "`internal/session`" + `.
4. Skills and AGENTS.md context are discovered when enabled.
5. ` + "`chatSystem`" + ` builds both flattened and segmented system prompts.
6. ` + "`agent.New`" + ` receives provider, tools, permission policy, system prompt, and optional restored messages.
7. ` + "`tui.Run`" + ` owns user interaction and saves the transcript after each send.

## Agent Loop Contract

The agent appends one user text message per ` + "`Send`" + ` call. Each provider response becomes an assistant message. If the assistant requests tools, Neo runs them, appends matching user ` + "`tool_result`" + ` blocks, and continues the provider loop until the assistant ends the turn or max turns is reached.
`
}

func cliPage() string {
	return generatedHeader + `# CLI

## Commands

| Command | Description |
| --- | --- |
| ` + "`neo`" + ` | Open interactive chat mode. |
| ` + "`neo chat`" + ` | Open interactive chat mode explicitly. |
| ` + "`neo sessions`" + ` | List saved chat sessions. |
| ` + "`neo resume <id>`" + ` | Resume a saved chat session. |
| ` + "`neo login`" + ` | Log in to an OpenAI ChatGPT/Codex subscription with OAuth. |
| ` + "`neo logout`" + ` | Remove stored OpenAI subscription credentials. |
| ` + "`neo help`" + ` | Print usage. |

## Environment

- ` + "`ANTHROPIC_API_KEY`" + ` is required when ` + "`provider: anthropic`" + `.
- ` + "`OPENAI_API_KEY`" + ` is required when ` + "`provider: openai`" + ` uses ` + "`openai_auth: api_key`" + `.
- ` + "`openai_auth: subscription`" + ` uses stored ChatGPT/Codex OAuth credentials created by ` + "`neo login`" + ` instead of an API key.

## Runtime Notes

- ` + "`neo`" + ` with no subcommand defaults to chat.
- ` + "`neo login`" + ` opens an OpenAI authorization URL, receives the loopback callback, and stores refreshable subscription credentials in ` + "`~/.neo/auth.json`" + ` with file permissions intended to protect secrets.
- ` + "`neo logout`" + ` deletes the stored OpenAI subscription credential entry.
- Resuming a session attempts to change into the saved session cwd. If unavailable, Neo warns and stays in the current directory.
- Session saves happen after each user turn through the TUI ` + "`WithAfterSend`" + ` callback.
`
}

func configPage(configYAML string) string {
	return generatedHeader + `# Configuration

Neo loads the first available config:

1. ` + "`./neo.yaml`" + `
2. ` + "`~/.neo/config.yaml`" + `
3. Embedded defaults from ` + "`internal/config/defaults/neo.yaml`" + `

First hit wins. Config files are not merged.

## Default Config

` + "```yaml" + `
` + strings.TrimSpace(configYAML) + `
` + "```" + `

## Provider Selection

| Config | Auth source | Provider adapter |
| --- | --- | --- |
| ` + "`provider: anthropic`" + ` | ` + "`ANTHROPIC_API_KEY`" + ` | ` + "`internal/llm/anthropic`" + ` |
| ` + "`provider: openai`" + ` with ` + "`openai_auth: api_key`" + ` | ` + "`OPENAI_API_KEY`" + ` | ` + "`internal/llm/openai.Client`" + ` |
| ` + "`provider: openai`" + ` with ` + "`openai_auth: subscription`" + ` | ChatGPT/Codex OAuth credentials from ` + "`~/.neo/auth.json`" + ` | ` + "`internal/llm/openai.CodexClient`" + ` |

Subscription credentials are created with ` + "`neo login`" + ` and removed with ` + "`neo logout`" + `. The docs describe only where credentials live and which flow uses them; token values are never generated into developer docs.

## Feature Flags

Each feature flag is tri-state in Go: absent means use the built-in default, while explicit ` + "`false`" + ` disables that capability.

| Flag | Default | Effect |
| --- | --- | --- |
| ` + "`agents_file`" + ` | ` + "`true`" + ` | Load AGENTS.md into the chat system prompt. |
| ` + "`skills`" + ` | ` + "`true`" + ` | Discover skills and expand $name references. |
| ` + "`prompt_caching`" + ` | ` + "`true`" + ` | Mark the stable system prompt prefix as cacheable when the provider supports it. |

## Permissions

` + "`permissions.mode`" + ` defaults to ` + "`ask`" + `.

| Mode | Effect |
| --- | --- |
| ` + "`ask`" + ` | Allow read/search tools inside the repo root; ask before bash and file mutations. |
| ` + "`trusted`" + ` | Allow built-in tools, while still denying path-shaped file tools outside the repo root. |
| ` + "`readonly`" + ` | Allow read/search tools only; deny bash and file mutations. |
`
}

func sessionsPage() string {
	return generatedHeader + `# Sessions

Neo stores resumable conversations under ` + "`~/.neo/sessions/`" + ` by default.

## Files

| File | Purpose |
| --- | --- |
| ` + "`index.json`" + ` | Metadata index used by ` + "`neo sessions`" + `. |
| ` + "`<session-id>.json`" + ` | Full session metadata and transcript. |

Session files are written atomically with a sibling temp file and rename.

## Metadata

| Field | Meaning |
| --- | --- |
| ` + "`id`" + ` | Session identifier, generated as ` + "`sess_<hex>`" + ` when absent. |
| ` + "`title`" + ` | Derived from the first non-empty user text if not set. |
| ` + "`source`" + ` | Origin of the session, default ` + "`tui`" + `. |
| ` + "`external`" + ` | Optional external transport key. |
| ` + "`cwd`" + ` | Working directory captured for resume. |
| ` + "`model`" + ` | Model used by the session. |
| ` + "`created_at`" + ` | UTC creation timestamp. |
| ` + "`updated_at`" + ` | UTC update timestamp. |

## Gateway Mapping

Gateways should reuse the same store instead of inventing another transcript format. Use ` + "`source`" + ` plus ` + "`external`" + ` to map transport conversations onto Neo sessions.

Examples:

- Telegram DM: ` + "`source=telegram`" + `, ` + "`external=chat:<id>`" + `
- Slack thread: ` + "`source=slack`" + `, ` + "`external=channel:<id>:thread:<ts>`" + `
`
}

func toolsPage(specs []llm.ToolSpec) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("# Tools\n\n")
	b.WriteString("Neo exposes a small built-in tool surface to the model.\n\n")
	b.WriteString("| Tool | Description |\n")
	b.WriteString("| --- | --- |\n")
	for _, spec := range specs {
		fmt.Fprintf(&b, "| `%s` | %s |\n", spec.Name, escapeTable(spec.Description))
	}
	b.WriteString("\n## Schemas\n\n")
	for _, spec := range specs {
		fmt.Fprintf(&b, "### `%s`\n\n", spec.Name)
		b.WriteString(spec.Description)
		b.WriteString("\n\n")
		schema, _ := json.MarshalIndent(spec.InputSchema, "", "  ")
		b.WriteString("```json\n")
		b.Write(schema)
		b.WriteString("\n```\n\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func promptCachingPage() string {
	return generatedHeader + `# Prompt Caching

Neo can pass the system prompt as ordered ` + "`llm.SystemBlock`" + ` values.

The flattened ` + "`Request.System`" + ` string remains available for providers that do not support structured system prompts. Providers that do support caching should prefer ` + "`Request.SystemBlocks`" + ` when present.

## Current Block Layout

1. Static base instructions plus skill catalog. This block is marked cacheable when ` + "`features.prompt_caching`" + ` is enabled.
2. Dynamic AGENTS.md project context. This block is not marked cacheable.

The goal is to cache stable instructions without letting changing project context evict that prefix.
`
}

func escapeTable(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
