package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/owainlewis/neo/internal/factory"
	"github.com/owainlewis/neo/internal/llm"
	"github.com/owainlewis/neo/internal/tools"
	"github.com/owainlewis/neo/internal/workflow"
)

const generatedHeader = "<!-- Generated by `go run ./cmd/neo-docs`. Do not edit by hand. -->\n\n"

type page struct {
	Path    string
	Content string
}

func main() {
	check := flag.Bool("check", false, "fail if generated developer docs are out of date")
	flag.Parse()

	pages, err := buildPages()
	if err != nil {
		fatal(err)
	}
	if *check {
		if err := checkPages(pages); err != nil {
			fatal(err)
		}
		return
	}
	if err := writePages(pages); err != nil {
		fatal(err)
	}
	for _, page := range pages {
		fmt.Printf("generated %s\n", page.Path)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

func buildPages() ([]page, error) {
	configYAML, err := os.ReadFile(filepath.Join("internal", "config", "defaults", "neo.yaml"))
	if err != nil {
		return nil, fmt.Errorf("read default config: %w", err)
	}
	specs := toolSpecs()
	return []page{
		{Path: filepath.Join("docs", "developer", "index.md"), Content: indexPage()},
		{Path: filepath.Join("docs", "developer", "architecture.md"), Content: architecturePage()},
		{Path: filepath.Join("docs", "developer", "cli.md"), Content: cliPage()},
		{Path: filepath.Join("docs", "developer", "config.md"), Content: configPage(string(configYAML))},
		{Path: filepath.Join("docs", "developer", "sessions.md"), Content: sessionsPage()},
		{Path: filepath.Join("docs", "developer", "tools.md"), Content: toolsPage(specs)},
		{Path: filepath.Join("docs", "developer", "prompt-caching.md"), Content: promptCachingPage()},
		{Path: filepath.Join("docs", "developer", "guides", "index.md"), Content: guidesIndexPage()},
		{Path: filepath.Join("docs", "developer", "guides", "agent-loop.md"), Content: agentLoopGuidePage()},
		{Path: filepath.Join("docs", "developer", "guides", "system-prompt.md"), Content: systemPromptGuidePage()},
		{Path: filepath.Join("docs", "developer", "guides", "tools.md"), Content: toolsGuidePage()},
		{Path: filepath.Join("docs", "developer", "guides", "permissions.md"), Content: permissionsGuidePage()},
		{Path: filepath.Join("docs", "developer", "guides", "providers.md"), Content: providersGuidePage()},
		{Path: filepath.Join("docs", "developer", "guides", "sessions.md"), Content: sessionsGuidePage()},
		{Path: filepath.Join("docs", "developer", "guides", "compaction.md"), Content: compactionGuidePage()},
		{Path: filepath.Join("docs", "developer", "guides", "memory.md"), Content: memoryGuidePage()},
	}, nil
}

func toolSpecs() []llm.ToolSpec {
	reg := tools.NewRegistry(
		factory.AgentTool{},
		tools.Bash{Timeout: 2 * time.Minute},
		tools.ReadFile{},
		tools.WriteFile{},
		tools.EditFile{},
		tools.Grep{Root: "."},
		tools.Glob{Root: "."},
		workflow.Tool{},
	)
	specs := reg.Specs()
	sort.Slice(specs, func(i, j int) bool { return specs[i].Name < specs[j].Name })
	return specs
}

func writePages(pages []page) error {
	for _, page := range pages {
		if err := os.MkdirAll(filepath.Dir(page.Path), 0o755); err != nil {
			return fmt.Errorf("create %s: %w", filepath.Dir(page.Path), err)
		}
		if err := os.WriteFile(page.Path, []byte(page.Content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", page.Path, err)
		}
	}
	return nil
}

func checkPages(pages []page) error {
	var stale []string
	for _, page := range pages {
		got, err := os.ReadFile(page.Path)
		if err != nil {
			stale = append(stale, page.Path)
			continue
		}
		if !bytes.Equal(got, []byte(page.Content)) {
			stale = append(stale, page.Path)
		}
	}
	if len(stale) > 0 {
		return fmt.Errorf("developer docs are out of date; run `go run ./cmd/neo-docs`: %s", strings.Join(stale, ", "))
	}
	return nil
}

func indexPage() string {
	return generatedHeader + `# Neo Developer Docs

These docs are generated from the repository and are intended for both humans and Neo itself.

Start here when changing Neo:

- [Architecture](architecture.md) explains the module boundaries.
- [CLI](cli.md) documents commands and startup flow.
- [Configuration](config.md) documents config loading and feature flags.
- [Sessions](sessions.md) documents persisted conversations and gateway mapping.
- [Tools](tools.md) documents the built-in tool surface.
- [Prompt caching](prompt-caching.md) documents structured system prompt blocks.
- [Teaching guides](guides/index.md) explain the core ideas in plain language.

Regenerate:

` + "```bash" + `
go run ./cmd/neo-docs
` + "```" + `

Check:

` + "```bash" + `
go run ./cmd/neo-docs --check
` + "```" + `
`
}

func architecturePage() string {
	return generatedHeader + `# Architecture

Neo is a small Go coding agent. The core agent loop is policy-free: it owns message state, calls an LLM provider, emits events, and runs injected tools. Product behavior is layered around that loop.

## Main Modules

| Path | Responsibility |
| --- | --- |
| ` + "`cmd/neo/`" + ` | CLI entry point, command dispatch, chat session startup. |
| ` + "`cmd/neo-docs/`" + ` | Deterministic developer documentation generator. |
| ` + "`internal/agent/`" + ` | Core agent loop, transcript state, event model, tool-use continuation. |
| ` + "`internal/auth/`" + ` | OpenAI ChatGPT/Codex device-code login, token refresh, and stored subscription credentials. |
| ` + "`internal/compact/`" + ` | Compaction interface, summarizing compactor, and safe split helpers. |
| ` + "`internal/config/`" + ` | Config discovery, defaults, and feature flags. |
| ` + "`internal/factory/`" + ` | Subagent runtime for the chat ` + "`agent`" + ` tool: supervisor budgets, node tree, and event stream. |
| ` + "`internal/llm/`" + ` | Provider-neutral request/response types and system prompt blocks. |
| ` + "`internal/llm/anthropic/`" + ` | Anthropic provider adapter. |
| ` + "`internal/llm/openai/`" + ` | OpenAI provider adapters for API-key Responses API calls and ChatGPT/Codex subscription calls. |
| ` + "`internal/llm/chatcompletions/`" + ` | Reusable OpenAI-compatible Chat Completions adapter. |
| ` + "`internal/llm/openrouter/`" + ` | OpenRouter provider setup and defaults. |
| ` + "`internal/permission/`" + ` | Tool-call permission policy and workspace path boundary checks. |
| ` + "`internal/projectctx/`" + ` | AGENTS.md, memory.md, and git-context discovery plus prompt augmentation. |
| ` + "`internal/session/`" + ` | File-backed session metadata and transcripts. |
| ` + "`internal/skills/`" + ` | Skill discovery, catalog rendering, and $name expansion. |
| ` + "`internal/tools/`" + ` | Built-in tools exposed to the model. |
| ` + "`internal/tui/`" + ` | Bubble Tea terminal UI and transcript rendering. |
| ` + "`internal/workspace/`" + ` | Workspace helpers shared by project-context features. |

## Chat Startup Flow

1. ` + "`cmd/neo`" + ` loads config.
2. ` + "`mustProvider`" + ` selects Anthropic, OpenAI, or OpenRouter. OpenAI defaults to API-key auth; ` + "`openai_auth: subscription`" + ` builds the Codex subscription provider from stored device-code credentials.
3. The CLI creates or loads a session from ` + "`internal/session`" + `.
4. Skills, AGENTS.md, project memory, and lightweight git context are discovered when enabled.
5. ` + "`chatSystem`" + ` builds both flattened and segmented system prompts.
6. ` + "`agent.New`" + ` receives provider, tools, permission policy, system prompt, and optional restored messages.
7. ` + "`tui.Run`" + ` owns user interaction and saves the transcript after each send.

## Agent Loop Contract

The agent appends one user text message per ` + "`Send`" + ` call. Each provider response becomes an assistant message. If the assistant requests tools, Neo runs them, caps oversized output before it enters user ` + "`tool_result`" + ` blocks, and continues the provider loop until the assistant ends the turn or max turns is reached.
`
}

func cliPage() string {
	return generatedHeader + `# CLI

## Commands

| Command | Description |
| --- | --- |
| ` + "`neo`" + ` | Open interactive chat mode. |
| ` + "`neo chat`" + ` | Open interactive chat mode explicitly. |
| ` + "`neo sessions`" + ` | List saved chat sessions. |
| ` + "`neo resume <id>`" + ` | Resume a saved chat session. |
| ` + "`neo login`" + ` | Log in to an OpenAI ChatGPT/Codex subscription with device-code auth. |
| ` + "`neo logout`" + ` | Remove stored OpenAI subscription credentials. |
| ` + "`neo help`" + ` | Print usage. |

## Environment

- ` + "`ANTHROPIC_API_KEY`" + ` is required when ` + "`provider: anthropic`" + `.
- ` + "`OPENAI_API_KEY`" + ` is required when ` + "`provider: openai`" + ` uses ` + "`openai_auth: api_key`" + `.
- ` + "`OPENROUTER_API_KEY`" + ` is required when ` + "`provider: openrouter`" + `.
- ` + "`openai_auth: subscription`" + ` uses stored ChatGPT/Codex device-code credentials created by ` + "`neo login`" + ` instead of an API key.

## Runtime Notes

- ` + "`neo`" + ` with no subcommand defaults to chat.
- ` + "`neo login`" + ` prints the OpenAI Codex device-code URL and one-time code, then stores refreshable subscription credentials in ` + "`~/.neo/auth.json`" + ` with file permissions intended to protect secrets.
- ` + "`neo logout`" + ` deletes the stored OpenAI subscription credential entry.
- Resuming a session attempts to change into the saved session cwd. If unavailable, Neo warns and stays in the current directory.
- Session saves happen after each user turn through the TUI ` + "`WithAfterSend`" + ` callback.
`
}

func configPage(configYAML string) string {
	return generatedHeader + `# Configuration

Neo loads the first available config:

1. ` + "`./neo.yaml`" + `
2. ` + "`~/.neo/config.yaml`" + `
3. Embedded defaults from ` + "`internal/config/defaults/neo.yaml`" + `

First hit wins. Config files are not merged.

## Default Config

` + "```yaml" + `
` + strings.TrimSpace(configYAML) + `
` + "```" + `

## Provider Selection

| Config | Auth source | Provider adapter |
| --- | --- | --- |
| ` + "`provider: anthropic`" + ` | ` + "`ANTHROPIC_API_KEY`" + ` | ` + "`internal/llm/anthropic`" + ` |
| ` + "`provider: openai`" + ` with ` + "`openai_auth: api_key`" + ` | ` + "`OPENAI_API_KEY`" + ` | ` + "`internal/llm/openai.Client`" + ` |
| ` + "`provider: openai`" + ` with ` + "`openai_auth: subscription`" + ` | ChatGPT/Codex device-code credentials from ` + "`~/.neo/auth.json`" + ` | ` + "`internal/llm/openai.CodexClient`" + ` |
| ` + "`provider: openrouter`" + ` | ` + "`OPENROUTER_API_KEY`" + ` | ` + "`internal/llm/openrouter`" + ` |

Subscription credentials are created with ` + "`neo login`" + ` and removed with ` + "`neo logout`" + `. The docs describe only where credentials live and which flow uses them; token values are never generated into developer docs.

## Feature Flags

Each feature flag is tri-state in Go: absent means use the built-in default, while explicit ` + "`false`" + ` disables that capability.

| Flag | Default | Effect |
| --- | --- | --- |
| ` + "`agents_file`" + ` | ` + "`true`" + ` | Load AGENTS.md into the chat system prompt. |
| ` + "`memory`" + ` | ` + "`true`" + ` | Load and update project-root ` + "`memory.md`" + `. |
| ` + "`skills`" + ` | ` + "`true`" + ` | Discover skills and expand $name references. |
| ` + "`prompt_caching`" + ` | ` + "`true`" + ` | Mark the stable system prompt prefix as cacheable when the provider supports it. |

## Permissions

` + "`permissions.mode`" + ` defaults to ` + "`trusted`" + `.

| Mode | Effect |
| --- | --- |
| ` + "`trusted`" + ` | Allow built-in tools; ask before high-risk bash commands; deny path-shaped file tools outside the repo root. |
| ` + "`ask`" + ` | Allow read/search tools inside the repo root; ask before bash and file mutations. |
| ` + "`readonly`" + ` | Allow read/search tools only; deny bash and file mutations. |
`
}

func sessionsPage() string {
	return generatedHeader + `# Sessions

Neo stores resumable conversations under ` + "`~/.neo/sessions/`" + ` by default.

## Files

| File | Purpose |
| --- | --- |
| ` + "`index.json`" + ` | Metadata index used by ` + "`neo sessions`" + `. |
| ` + "`<session-id>.json`" + ` | Full session metadata and transcript. |

Session files are written atomically with a sibling temp file and rename.

## Resume Surfaces

- ` + "`neo sessions`" + ` lists saved sessions from the shell.
- ` + "`neo resume <id>`" + ` resumes a session from the shell and restores its saved cwd before tools are created.
- ` + "`/sessions`" + ` opens an in-TUI session browser with search and cwd/all filtering. The in-TUI browser only resumes sessions from the current cwd, because tools and permissions are already bound to that workspace.

## Metadata

| Field | Meaning |
| --- | --- |
| ` + "`id`" + ` | Session identifier, generated as ` + "`sess_<hex>`" + ` when absent. |
| ` + "`title`" + ` | Derived from the first non-empty user text if not set. |
| ` + "`source`" + ` | Origin of the session, default ` + "`tui`" + `. |
| ` + "`external`" + ` | Optional external transport key. |
| ` + "`cwd`" + ` | Working directory captured for resume. |
| ` + "`model`" + ` | Model used by the session. |
| ` + "`created_at`" + ` | UTC creation timestamp. |
| ` + "`updated_at`" + ` | UTC update timestamp. |

## Gateway Mapping

Gateways should reuse the same store instead of inventing another transcript format. Use ` + "`source`" + ` plus ` + "`external`" + ` to map transport conversations onto Neo sessions.

Examples:

- Telegram DM: ` + "`source=telegram`" + `, ` + "`external=chat:<id>`" + `
- Slack thread: ` + "`source=slack`" + `, ` + "`external=channel:<id>:thread:<ts>`" + `
`
}

func toolsPage(specs []llm.ToolSpec) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("# Tools\n\n")
	b.WriteString("Neo exposes a small built-in tool surface to the model.\n\n")
	b.WriteString("| Tool | Description |\n")
	b.WriteString("| --- | --- |\n")
	for _, spec := range specs {
		fmt.Fprintf(&b, "| `%s` | %s |\n", spec.Name, escapeTable(spec.Description))
	}
	b.WriteString("\n## Schemas\n\n")
	for _, spec := range specs {
		fmt.Fprintf(&b, "### `%s`\n\n", spec.Name)
		b.WriteString(spec.Description)
		b.WriteString("\n\n")
		schema, _ := json.MarshalIndent(spec.InputSchema, "", "  ")
		b.WriteString("```json\n")
		b.Write(schema)
		b.WriteString("\n```\n\n")
	}
	return strings.TrimRight(b.String(), "\n") + "\n"
}

func promptCachingPage() string {
	return generatedHeader + `# Prompt Caching

Neo can pass the system prompt as ordered ` + "`llm.SystemBlock`" + ` values.

The flattened ` + "`Request.System`" + ` string remains available for providers that do not support structured system prompts. Providers that do support caching should prefer ` + "`Request.SystemBlocks`" + ` when present.

## Current Block Layout

1. Static base instructions plus skill catalog. This block is marked cacheable when ` + "`features.prompt_caching`" + ` is enabled.
2. Dynamic AGENTS.md project context. This block is not marked cacheable.
3. Dynamic ` + "`memory.md`" + ` project context. This block is not marked cacheable.
4. Dynamic git context (` + "`branch`" + `, ` + "`git status --short`" + `, ` + "`git log --oneline -5`" + `). This block is not marked cacheable.

The goal is to cache stable instructions without letting changing project context evict that prefix.
`
}

func guidesIndexPage() string {
	return generatedHeader + `# Teaching Guides

These guides explain Neo's core features in plain language. The reference docs say what exists; these guides explain why it exists, how it works, and how to change it safely.

## Guides

| Guide | What it explains |
| --- | --- |
| [Agent loop](agent-loop.md) | How one user message becomes model calls, tool calls, and a final answer. |
| [System prompt](system-prompt.md) | What instructions Neo gives the model and how project context is added. |
| [Tools](tools.md) | How Neo lets the model read files, search, run commands, and edit. |
| [Permissions](permissions.md) | Why approvals exist and how ` + "`ask`" + `, ` + "`trusted`" + `, and ` + "`readonly`" + ` work. |
| [Providers](providers.md) | How Anthropic, OpenAI API-key auth, and OpenAI subscription auth plug in. |
| [Sessions](sessions.md) | How Neo saves and resumes conversations. |
| [Compaction](compaction.md) | Why long chats need context management and what Neo has today. |
| [Memory](memory.md) | What memory means for a coding agent and what should stay out of scope. |

## PR Readiness Loops

Use a normal prompt for one bounded change.

Use a persistent PR-readiness goal when external state can change after the first pass, such as CI, generated-doc checks, or automated review comments.

That loop should re-read live PR state, fix only actionable failures, push updates, then re-check until the PR is ready or a real blocker repeats.

## How To Read These

Each guide uses the same shape:

1. The simple idea.
2. The problem it solves.
3. How Neo implements it today.
4. How to customize or extend it.
5. What to be careful about.
`
}

func agentLoopGuidePage() string {
	return generatedHeader + `# Agent Loop

## The Simple Idea

The agent loop is Neo's heartbeat. A user sends a message, the model answers, Neo runs any requested tools, then the model continues until it has a final answer.

Think of it like:

1. User asks for work.
2. Model decides what to do.
3. Neo runs tools the model asked for.
4. Tool results go back to the model.
5. Repeat until the model is done.

## The Problem

Coding agents need more than one model response. A model might first need to inspect files, then run a command, then edit a file, then run tests. That means one user turn can contain several model/tool steps.

The tricky part is preserving the transcript correctly. If the model asks for a tool, the next provider request must include the matching tool result. Splitting those apart can break provider APIs and confuse the model.

## How Neo Solves It

The core loop lives in ` + "`internal/agent`" + `. It is deliberately policy-free:

- It stores messages.
- It calls an ` + "`llm.Provider`" + `.
- It emits events for the TUI.
- It runs injected tools.
- It appends tool results before continuing.

It does not know about coding style, AGENTS.md, skills, permissions, or the terminal UI. Those are layered around it.

## The Important Invariant

Every assistant ` + "`tool_use`" + ` must be followed by a matching user ` + "`tool_result`" + ` before the transcript is sent back to the provider.

Neo builds the assistant message and tool results together before committing them to the transcript. That keeps the conversation valid even when a tool fails.

Oversized tool output is capped at the agent boundary before it enters the transcript or session payload. The capped content includes a visible truncation marker with the original byte size and line count.

## How To Extend It

Add behavior around the loop, not inside it, unless the behavior is truly provider/tool-turn mechanics.

Good extensions:

- Add a new tool to ` + "`internal/tools`" + ` and inject it through the registry.
- Add a new provider that implements ` + "`llm.Provider`" + `.
- Add prompt context before constructing the agent.
- Add a compactor through the ` + "`compact.Compactor`" + ` interface.

Risky extensions:

- Teaching the loop about project files.
- Putting UI behavior in the loop.
- Making the loop decide permissions itself.

## Where To Look

- ` + "`internal/agent/agent.go`" + `: the loop and event model.
- ` + "`internal/llm/provider.go`" + `: provider-neutral message and tool types.
- ` + "`internal/tools/`" + `: built-in tools the loop can run.
`
}

func systemPromptGuidePage() string {
	return generatedHeader + `# System Prompt

## The Simple Idea

The system prompt is the agent's instruction sheet. It tells the model what Neo is, what behavior to prefer, and what extra project context is available.

If the user message is the task, the system prompt is the job description.

## The Problem

A coding agent needs stable instructions, but it also needs local context. Some context is almost always the same, such as "prefer small verified changes." Other context changes by project, such as AGENTS.md files, project memory, or available skills.

If all of that is mashed into one giant string, it is harder to understand, harder to cache, and harder to customize.

## How Neo Solves It

Neo builds the prompt in ordered blocks:

1. A stable base prompt plus the skill catalog.
2. Dynamic project instructions from AGENTS.md files.
3. Dynamic project memory from ` + "`memory.md`" + ` when enabled.
4. Dynamic git context captured at session start.

The flattened prompt is still available for providers that only accept a string. Providers that support structured system prompts can use ` + "`llm.SystemBlock`" + ` values instead.

## What Goes Where

| Source | Purpose |
| --- | --- |
| Base prompt | Neo's default behavior: focused coding agent, read files, make small verified changes. |
| Skill catalog | Names and descriptions of available skills. Full skill bodies are only expanded when invoked. |
| AGENTS.md | Project or user instructions that should guide work in this repo. |
| ` + "`memory.md`" + ` | Durable project facts or preferences the user saved for future sessions. |
| Git context | Branch, working tree status, and recent commits captured when the session starts in a repo. |

## How To Customize It

Use AGENTS.md for durable project instructions. For example:

` + "```md" + `
Read docs/developer/index.md before making changes.
Do not edit generated docs by hand.
Run go test ./... after Go changes.
` + "```" + `

Use skills for reusable workflows that should only apply when requested, such as review or commit behavior.

Change the base prompt only when the default personality or operating rules of Neo itself should change.

## What To Be Careful About

Always-loaded prompt text costs tokens every turn. Keep stable instructions short. Put big or optional workflows in skills, tools, or searchable history instead of stuffing them into the system prompt.

## Where To Look

- ` + "`cmd/neo/main.go`" + `: chat startup and prompt assembly.
- ` + "`internal/projectctx`" + `: AGENTS.md, memory.md, and git-context discovery and rendering.
- ` + "`internal/skills`" + `: skill catalog and expansion.
- ` + "`internal/llm/provider.go`" + `: ` + "`SystemBlock`" + `.
`
}

func toolsGuidePage() string {
	return generatedHeader + `# Tools

## The Simple Idea

Tools are the agent's hands. The model can think and write text, but tools let it inspect the repo, run commands, and change files.

## The Problem

A model cannot directly read your filesystem or run tests. Without tools, it has to guess. With tools, it can inspect reality before acting.

The danger is that tools have side effects. A shell command or file write can change the machine, so tools must be small, inspectable, and permissioned.

## How Neo Solves It

Neo exposes a small built-in tool surface:

- ` + "`read_file`" + `: read files.
- ` + "`grep`" + `: search file contents and return structured JSON matches.
- ` + "`glob`" + `: find files by pattern and return structured JSON paths.
- ` + "`bash`" + `: run shell commands.
- ` + "`write_file`" + `: overwrite or create files.
- ` + "`edit_file`" + `: replace one exact string.

Each tool implements the same interface:

` + "```go" + `
type Tool interface {
    Name() string
    Spec() llm.ToolSpec
    Run(ctx context.Context, input map[string]any) (string, error)
}
` + "```" + `

The model sees tool specs. Neo runs the tool and feeds the result back into the conversation.

## Why The Tool Surface Is Small

Small tools are easier to trust and easier to teach. For example, ` + "`edit_file`" + ` replaces exactly one occurrence. If the target text is missing or appears more than once, it fails instead of guessing.

That makes failures useful: the model can inspect again and try a safer edit.

## How To Add A Tool

1. Add a type in ` + "`internal/tools`" + `.
2. Implement ` + "`Name`" + `, ` + "`Spec`" + `, and ` + "`Run`" + `.
3. Register it in ` + "`cmd/neo/main.go`" + `.
4. Add tests for success, bad input, and edge cases.
5. Update docs by running ` + "`go run ./cmd/neo-docs`" + `.

## What To Be Careful About

- Treat errors as data. Return useful output when a tool fails.
- Keep file tools inside the workspace boundary.
- Prefer structured tools over shell commands for common operations.
- Do not make one giant tool that does everything.

## Where To Look

- ` + "`internal/tools/tool.go`" + `: tool interface and registry.
- ` + "`internal/tools/fs.go`" + `: file tools.
- ` + "`internal/tools/search.go`" + `: grep and glob.
- ` + "`internal/tools/bash.go`" + `: shell execution.
`
}

func permissionsGuidePage() string {
	return generatedHeader + `# Permissions

## The Simple Idea

Permissions decide whether a tool call runs immediately, asks the user, or is denied.

Think of it as the safety latch between "the model wants to do this" and "Neo actually does it."

## The Problem

Coding agents need powerful tools. They may run shell commands or edit files. That is useful, but it also means a bad tool call can make a mess.

Approvals keep the user in control, especially for side effects.

## How Neo Solves It

Neo has three permission modes:

| Mode | What happens |
| --- | --- |
| ` + "`trusted`" + ` | Built-in tools run automatically, except high-risk bash commands ask first. Workspace path checks still apply. |
| ` + "`ask`" + ` | Read/search tools run automatically. Bash and file mutations ask first. |
| ` + "`readonly`" + ` | Read/search tools run. Bash and file mutations are denied. |

By default, Neo uses ` + "`trusted`" + ` to avoid prompting for routine coding work while still pausing before commands such as ` + "`rm -rf`" + `, ` + "`sudo`" + `, recursive ownership/permission changes, ` + "`git clean -fd`" + `, and ` + "`git reset --hard`" + `.

Configure it in ` + "`neo.yaml`" + `:

` + "```yaml" + `
permissions:
  mode: trusted
` + "```" + `

For stricter approval prompts:

` + "```yaml" + `
permissions:
  mode: ask
` + "```" + `

## Workspace Boundaries

For path-shaped tools, Neo checks that paths stay inside the workspace root. This still matters in ` + "`trusted`" + ` mode.

The point of ` + "`trusted`" + ` is to stop asking for every mutation, not to let the agent write anywhere on the machine.

## Approval Previews

When a write or edit asks for approval, Neo shows a preview. Long previews are truncated in the TUI so the approval question stays visible.

The preview is there to answer: "what am I about to allow?"

## How To Extend It

The policy interface is small:

` + "```go" + `
type Policy interface {
    Decide(ctx context.Context, req Request) Result
}
` + "```" + `

Future policies could add per-tool rules, command allowlists, or stronger sandboxing without changing the core agent loop.

## Where To Look

- ` + "`internal/permission/policy.go`" + `: permission modes and path checks.
- ` + "`internal/agent/agent.go`" + `: approval hook.
- ` + "`internal/tui/blocks.go`" + `: approval rendering.
- ` + "`internal/agent/preview.go`" + `: write/edit previews.
`
}

func providersGuidePage() string {
	return generatedHeader + `# Providers

## The Simple Idea

A provider is the adapter between Neo and a model API. Neo speaks its own small internal language; providers translate that into Anthropic or OpenAI requests.

## The Problem

Different model APIs use different request shapes, response shapes, tool-call formats, auth methods, retry behavior, and token accounting. OpenRouter uses an OpenAI-compatible Chat Completions shape while OpenAI itself uses the newer Responses API in Neo.

Neo should not bake any one provider into the agent loop.

## How Neo Solves It

Neo defines one provider interface:

` + "```go" + `
type Provider interface {
    Name() string
    Complete(ctx context.Context, req Request) (*Response, error)
}
` + "```" + `

The core loop sends an ` + "`llm.Request`" + `. The provider returns an ` + "`llm.Response`" + `. Everything provider-specific stays behind the adapter.

## Current Providers

| Provider config | Auth | Adapter |
| --- | --- | --- |
| ` + "`provider: anthropic`" + ` | ` + "`ANTHROPIC_API_KEY`" + ` | ` + "`internal/llm/anthropic`" + ` |
| ` + "`provider: openai`" + ` + ` + "`openai_auth: api_key`" + ` | ` + "`OPENAI_API_KEY`" + ` | ` + "`internal/llm/openai.Client`" + ` |
| ` + "`provider: openai`" + ` + ` + "`openai_auth: subscription`" + ` | ` + "`neo login`" + ` device-code credentials | ` + "`internal/llm/openai.CodexClient`" + ` |
| ` + "`provider: openrouter`" + ` | ` + "`OPENROUTER_API_KEY`" + ` | ` + "`internal/llm/openrouter`" + ` |

## How Models Are Chosen

The config ` + "`model`" + ` value is passed through to the provider. If omitted, Neo chooses a provider-aware default.

In the TUI, ` + "`/model`" + ` opens a model picker. It changes the active model for the current session and saves that session metadata.

## What To Be Careful About

- Provider adapters should translate, not decide product behavior.
- Retry and response parsing belong in provider packages.
- The core agent loop should not care whether a response came from Anthropic or OpenAI.
- Subscription/Codex auth is experimental and should be documented carefully.

## Where To Look

- ` + "`internal/llm/provider.go`" + `: provider-neutral types.
- ` + "`internal/llm/anthropic`" + `: Anthropic adapter.
- ` + "`internal/llm/openai`" + `: OpenAI adapters.
- ` + "`internal/llm/chatcompletions`" + `: reusable OpenAI-compatible Chat Completions translation.
- ` + "`internal/llm/openrouter`" + `: OpenRouter adapter wiring.
- ` + "`internal/auth`" + `: subscription credential storage and refresh.
- ` + "`cmd/neo/main.go`" + `: provider selection.
`
}

func sessionsGuidePage() string {
	return generatedHeader + `# Sessions

## The Simple Idea

A session is a saved conversation. It lets Neo stop and later continue with the same transcript.

In Codex terms, it is close to a thread.

## The Problem

Coding work often takes more than one terminal run. Without sessions, every restart loses the transcript, tool results, model choice, cwd, and title.

Neo needs a durable place to store that conversation.

## How Neo Solves It

Neo stores sessions under ` + "`~/.neo/sessions/`" + `:

- ` + "`index.json`" + `: metadata for listing.
- ` + "`<session-id>.json`" + `: full transcript and metadata.

The TUI saves after each user turn. Resuming a session restores the old messages into the agent.

## Ways To Resume

From the shell:

` + "```bash" + `
neo sessions
neo resume <session-id>
` + "```" + `

Inside the TUI:

` + "```text" + `
/sessions
` + "```" + `

The TUI browser supports search, arrow-key navigation, cwd/all filtering, and enter-to-resume.

## Why CWD Matters

Tools and permissions are bound to the workspace when the TUI starts. For that reason, the in-TUI browser only resumes sessions from the current cwd. Cross-project sessions should be resumed from the shell with ` + "`neo resume <id>`" + ` so Neo can restore the saved cwd before creating tools.

## Future Memory Connection

Session search is a natural form of episodic memory: "what happened before?" Neo already saves transcripts, so a future memory search can query these sessions.

## Where To Look

- ` + "`internal/session/session.go`" + `: file-backed session store.
- ` + "`cmd/neo/main.go`" + `: create, list, resume, and save wiring.
- ` + "`internal/tui/sessions.go`" + `: in-TUI session browser.
`
}

func compactionGuidePage() string {
	return generatedHeader + `# Compaction

## The Simple Idea

Compaction is how an agent keeps a long conversation small enough to fit in the model's context window.

If the transcript is a backpack, compaction is repacking it so the important things still fit.

## The Problem

Every model has a context limit. Long coding sessions can accumulate user messages, assistant messages, tool calls, tool results, diffs, test output, and screenshots.

If the transcript gets too large, the next provider call may fail or become wastefully expensive.

## How Neo Solves It Today

Neo summarizes old turns once the transcript gets large:

- ` + "`compact.Compactor`" + ` is the interface; the agent calls it before every provider call.
- ` + "`compact.Summarizer`" + ` is wired in by the chat command. When the estimated transcript size passes a trigger (~100k tokens), it asks the provider to summarize the oldest turns and replaces them with a single user message carrying the summary. The most recent messages are kept verbatim.
- ` + "`NoCompaction`" + ` is the fallback when no compactor is configured.
- ` + "`SafeSplitPoint`" + ` picks the cut so strategies avoid invalid transcript splits.

The important safety rule is: never keep a ` + "`tool_result`" + ` without its matching ` + "`tool_use`" + `.

## Strategy Options

| Strategy | Idea | Status |
| --- | --- | --- |
| No compaction | Keep the transcript as-is. | Fallback when unconfigured. |
| Summarize old turns | Replace older conversation with a summary. | Current default (` + "`Summarizer`" + `). |
| Sliding window | Keep only the most recent safe chunk. | Future. |
| Token-budget compaction | Compact only when near a model's context limit. | Future, needs model catalog. |

## What Good Compaction Preserves

Good compaction keeps:

- the user's goal,
- decisions already made,
- files changed,
- commands run,
- unresolved errors,
- enough recent context for the model to continue.

It can drop:

- repeated logs,
- obsolete exploration,
- huge tool outputs once summarized,
- details that no longer affect the task.

## Where To Look

- ` + "`internal/compact/compact.go`" + `: compactor interface and safe split helper.
- ` + "`internal/agent/agent.go`" + `: compactor call before provider calls.
`
}

func memoryGuidePage() string {
	return generatedHeader + `# Memory

## The Simple Idea

Memory is what an agent carries across sessions.

For Neo, memory should stay narrow: useful project context for a coding agent, not broad personal-assistant memory.

## The Problem

Coding agents repeatedly rediscover the same project facts:

- generated docs must be updated through a generator,
- tests run with a specific command,
- a provider path is experimental,
- a design decision was made last week.

If those lessons are not saved somewhere, the agent starts cold each time.

## Three Kinds Of Memory

| Type | Meaning | Coding-agent example |
| --- | --- | --- |
| Episodic | What happened. | "Last session we decided not to add broad assistant memory." |
| Semantic | What is true. | "This repo is a Go CLI/TUI project." |
| Procedural | How to do things. | "Run ` + "`go test ./...`" + ` after Go changes." |

A simple shorthand: episodic is the diary, semantic is the facts, procedural is the playbook.

## What Neo Has Today

Neo now has a narrow, manual memory feature:

- project-local ` + "`memory.md`" + ` at the repo root,
- a user-entered ` + "`/memory <text>`" + ` slash command,
- prompt loading when ` + "`features.memory`" + ` is enabled.

Neo still keeps memory intentionally small. It does not expose an autonomous memory-writing tool to the model in this version.

## A Minimal Neo Memory Design

For a coding agent, the smallest useful memory feature is:

- ` + "`memory.md`" + ` at the project root for learned facts and conventions.
- ` + "`/memory <text>`" + ` to append a memory, with explicit user control.
- a distinct dynamic system-prompt section so loaded memory stays separate from base instructions and AGENTS.md.

That gives Neo durable project context without inventing automatic memory behavior too early.

## AGENTS.md vs MEMORY.md

AGENTS.md is instruction. It says how the agent should behave in this repo.

memory.md is learned context. It says what the agent or team learned while working.

Examples:

` + "```md" + `
# AGENTS.md
- Read docs/developer/index.md before changing Neo.
- Do not edit generated docs by hand.

# memory.md
- 2026-06-10: Memory stays project-specific and manual in V1.
- The /sessions browser only resumes sessions from the current cwd.
` + "```" + `

## What To Be Careful About

- Memory is prompt text, so it is a security surface.
- Always-loaded memory costs tokens every turn.
- Bad memory is worse than no memory.
- Session search should retrieve history on demand, not stuff every old conversation into context.

## Where To Look

- ` + "`internal/projectctx`" + `: AGENTS.md and memory.md loading.
- ` + "`internal/session`" + `: saved conversation history.
- ` + "`internal/skills`" + `: reusable procedural instructions.
`
}

func escapeTable(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}
